services:
  web:
    build: .
    container_name: securechat_flask
    volumes:
      - secure_uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - secure_net

  db:
    image: postgres:18.1-alpine
    container_name: securechat_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure_net
    
  nginx:
    image: nginx:alpine
    container_name: securechat_nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./app/static:/app/static
    depends_on:
      - web
    networks:
      - secure_net

  redis:
    image: redis:alpine
    container_name: securechat_redis
    restart: always
    expose:
      - "6379"
    networks:
      - secure_net

volumes:
  static_volume:
  postgres_data:
  secure_uploads:

networks:
  secure_net:
    driver: bridge